### ISSUE TITLE
FD Analysis - calculation of optical constants for sample and reference with thickness difference <0.1mm

### ISSUE THREAD

**Issue by CamTHz** [dotTHzTAG/CaTSper_MATLAB#4]
When calculating the absorption coefficient of a sample of 3.15 mm thickness and a reference of 3.10 mm thickness the optical constants are not coming out correctly. In the time-domain tab I can see that the respective thickness information is entered correctly in the .thz file but on the frequency-domain tab in the box 'FD Data Analysis' the thickness is only shown as 3.1 mm in each case. 

It looks like the calculation is carried out with the 3.1 mm thickness rather than the correct 3.10 and 3.15 mm thickness, i.e. the thickness difference between sample and reference of 0.05 mm.

**Comment by jl2112tag** [comment]
The value display format of the thickness edit fields are now changed to '%6.3f,' allowing for the accuracy of 1 micron.
