### ISSUE TITLE
Failed to read configuation JSON file error

### ISSUE THREAD

**Issue by CamTHz** [dotTHzTAG/CaTSper_MATLAB#6]
When starting the CaTSper.mlapp programme in Matlab an error message appears:

> Failed to read configuration JSON file: Could not open file config_ default.json. No such file or directory.

There is no .json file in the root directory. Can the .json file be stored with the default settings in a different path? Maybe the user root folder could be used so that the value for the .json file can remain constant.

<img width="445" alt="Screenshot 2024-07-24 at 12 03 19" src="https://github.com/user-attachments/assets/7dc12830-ce82-495e-8c97-fe5c444d83d3">

**Comment by jl2112tag** [comment]
Thanks for flagging up this. Now the configuration file (config_default.json) is available and can be downloaded. Please make sure that the file is in the same directory with CaTSper.mlapp file. Please note that when you install CaTSper using the installer the configuration file is included in the installer. For further instruction, please read the installation guide, https://github.com/dotTHzTAG/CaTSper.
