### ISSUE TITLE
Error message in Matlab

### ISSUE THREAD

**Issue by CamTHz** [dotTHzTAG/CaTSper_MATLAB#7]
After importing and deploying a .thz file Matlab throws up an error message when clicking on a file in the Measurement list on the left:

<img width="1630" alt="Screenshot 2024-07-24 at 12 09 57" src="https://github.com/user-attachments/assets/488294ab-98bc-4fab-9465-f52e8d6c899e">

The error message is:

> Error using strsplit
> First input must be either a character vector or a string scalar.
> 
> Error in CaTSper/MeasurementListBoxValueChanged (line 1320)
>             mdList = strsplit(mdDescription,',');
> 
> Error in appdesigner.internal.service.AppManagementService/executeCallback (line 172)
>                 callback(appOrUserComponent, event);
> 
> Error in matlab.apps.AppBase>@(source,event)executeCallback(ams,app,callback,requiresEventData,event) (line 62)
>             newCallback = @(source, event)executeCallback(ams, ...
>  
> Error using appdesservices.internal.interfaces.model.AbstractModel/executeUserCallback
> Error while evaluating ListBox PrivateValueChangedFcn.

This error message repeats every time I click on a file in the list on the left. The app works fine regardless but Matlab makes an annoying sound every time the error is triggered.

### Matlab Version
MATLAB R2023b Update 3
64-bit (maca64)

**Comment by CamTHz** [comment]
The error does not happen for all files, and I wonder whether it is related to the Measurement name containing : characters.

**Comment by jl2112tag** [comment]
The error occurs when the data file does not contain the metadata (or dataset) description. Now the description is optional and read when it exists.
